main/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^complete/?$', views.complete, name='complete'),
    url(r'^logout/?$', views.logout_user, name='logout'),
    url(r'^overview/?$', views.overview, name='overview'),
    url(r'^upload_simple/?$', views.upload_old, name='upload_old'),
    url(r'^about/?$', views.about, name='about'),
    url(r'^list/?$', views.list_files, name='list'),
    url(r'^delete/(?P<file_id>\w+)/?$', views.delete_file, name='delete')
]

oh_data_uploader/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns = [
    path('project-admin/', include('project_admin.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

project_admin/urls.py
from django.conf.urls import url

from . import views

app_name = 'project-admin'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^config-general-settings/?$',
        views.config_general_settings, name='config-general-settings'),
    url(r'^config-oh-settings/?$',
        views.config_oh_settings, name='config-oh-settings'),
    url(r'^config-file-settings/?$',
        views.config_file_settings, name='config-file-settings'),
    url(r'^config-homepage-text/?$',
        views.config_homepage_text, name='config-homepage-text'),
    url(r'^login/?$', views.admin_login, name='login'),
    url(r'^add-file/?$', views.add_file, name='add-file'),
    url(r'^delete-file/(?P<file_id>\w+)/?$', views.delete_file,
        name='delete-file'),
]

project_admin/models.py
from django.core.exceptions import ValidationError
from django.db import models
import json


class ProjectConfiguration(models.Model):
    """
    Store project configuration.
    """
    project_title = models.CharField(
        max_length=50,
        blank=True)
    oh_client_id = models.CharField(
        max_length=40,
        blank=True)
    oh_client_secret = models.CharField(
        max_length=128,
        blank=True)

    project_description = models.TextField(
        help_text='Project description, displayed on the front page.',
        blank=True)
    oh_activity_page = models.TextField(
        help_text='The URL where we can find your project in Open Humans.',
        blank=True)
    logo_url = models.TextField(
        blank=True,
        help_text='URL with logo of your project. If left blank, '
                  '/static/default_logo.png will be used.')
    more_info_url = models.TextField(
        blank=True,
        help_text='URL to find more information about your project.')

    about = models.TextField(blank=True)
    faq = models.TextField(blank=True)
    homepage_text = models.TextField(blank=True)
    overview = models.TextField(blank=True)
    upload_description = models.TextField(blank=True)

    @property
    def client_info(self):
        return {'client_id': self.oh_client_id,
                'client_secret': self.oh_client_secret}

    def save(self, *args, **kwargs):
        if ProjectConfiguration.objects.exists() and not self.pk:
            raise ValidationError('Only one ProjectConfiguration allowed')
        return super(ProjectConfiguration, self).save(*args, **kwargs)


class FileMetaData(models.Model):
    """
    Store file metadata
    """
    name = models.TextField(
        help_text='Name of the file (for representational purposes '
                  'in the project)'
    )
    description = models.TextField(
        help_text='Description of the type of data being uploaded.',
        blank=True)
    tags = models.TextField(
        help_text='List of tags that describe file uploads, stored as a '
                  'JSON-formatted array',
        blank=True)

    def get_tags(self):
        return ','.join(json.loads(self.tags)) if self.tags else ''

project_admin/views.py
from django.conf import settings
from django.contrib.auth import get_user_model, login
from django.shortcuts import redirect, render

from .models import ProjectConfiguration, FileMetaData
import json

User = get_user_model()


def home(request):
    """
    Main page for project config.
    """
    if request.user.username == 'admin':
        project_config = ProjectConfiguration.objects.get(id=1)
        files = FileMetaData.objects.all()
        for file in files:
            file.tags = file.get_tags()
        context = {'project_config': project_config, 'files': files}
        return render(request, 'project_admin/home.html', context=context)
    return redirect('project-admin:login')


def admin_login(request):
    """
    Log in as project admin.
    """
    if request.method == 'POST':
        if not settings.ADMIN_PASSWORD:
            return render(request, 'project_admin/login.html',
                          context={'error': 'ADMIN_PASSWORD environment '
                                   'variable needs to be set!'})
        elif request.POST['password'] == settings.ADMIN_PASSWORD:
            admin_user = User.objects.get(username='admin')
            login(request, admin_user,
                  backend='django.contrib.auth.backends.ModelBackend')
            return redirect('project-admin:home')
        else:
            return render(request, 'project_admin/login.html',
                          context={'error': 'Password incorrect.'})

    return render(request, 'project_admin/login.html')


def config_general_settings(request):
    """
    Update Open Humans project configuration.
    """
    if request.user.username != 'admin':
        return redirect('project-admin:home')

    if request.method == 'POST':
        project_config = ProjectConfiguration.objects.get(id=1)
        project_config.project_title = request.POST['project_title']
        project_config.project_description = request.POST[
            'project_description']
        project_config.more_info_url = request.POST['more_info_url']
        project_config.logo_url = request.POST['logo_url']
        project_config.save()
        return redirect('project-admin:home')

    return render(request, 'project_admin/config-general-settings.html')


def config_oh_settings(request):
    """
    Update Open Humans project configuration.
    """
    if request.user.username != 'admin':
        return redirect('project-admin:home')

    if request.method == 'POST':
        project_config = ProjectConfiguration.objects.get(id=1)
        project_config.oh_client_id = request.POST['client_id']
        project_config.oh_client_secret = request.POST['client_secret']
        project_config.oh_activity_page = request.POST['activity_page']
        project_config.save()
        return redirect('project-admin:home')

    return render(request, 'project_admin/config-oh-settings.html')


def config_file_settings(request):
    """
    Update file metadata settings
    """
    if request.user.username != 'admin':
        return redirect('project-admin:home')

    if request.method == 'POST':
        update_file_metadata(request.POST)
        return redirect('project-admin:home')

    files = FileMetaData.objects.all()
    for file in files:
        file.tags = file.get_tags()
    return render(request, 'project_admin/config-file-settings.html',
                  context={"files": files})


def config_homepage_text(request):
    """
    Update Open Humans project configuration.
    """
    if request.user.username != 'admin':
        return redirect('project-admin:home')

    if request.method == 'POST':
        project_config = ProjectConfiguration.objects.get(id=1)
        project_config.homepage_text = request.POST['homepage_text']
        project_config.about = request.POST['about']
        project_config.faq = request.POST['faq']
        project_config.overview = request.POST['overview']
        project_config.upload_description = request.POST['upload_description']
        project_config.save()
        return redirect('project-admin:home')

    return render(request, 'project_admin/config-homepage-text.html')


def add_file(request):
    """
    Add file metadata object
    """
    if request.user.username != 'admin':
        return redirect('project-admin:home')

    if request.method == 'POST':
        update_file_metadata(request.POST)
        file = FileMetaData.objects.create()
        file.name = "File {}".format(file.id)
        file.save()

    return redirect('project-admin:config-file-settings')


def delete_file(request, file_id):
    """
    Delete file metadata object
    """
    if request.user.username != 'admin':
        return redirect('project-admin:home')

    if request.method == 'POST':
        update_file_metadata(request.POST)
        file = FileMetaData.objects.get(id=file_id)
        file.delete()

    return redirect('project-admin:config-file-settings')


def update_file_metadata(metadata):
    files = FileMetaData.objects.all()
    for file in files:
        file.name = metadata["file_{}_name".format(file.id)]
        file.description = metadata["file_{}_description"
                                    .format(file.id)]
        file.tags = json.dumps(metadata["file_{}_tags"
                               .format(file.id)].split(","))
        file.save()

project_admin/templates/project_admin/config-file-settings.html
{% extends 'main/application.html' %}

{% block content %}
{% load utilities %}

<form action="{% url 'project-admin:config-file-settings' %}" method="post">
  {% csrf_token %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th style="width: 32%;">Name</th>
        <th style="width: 32%;">Description</th>
        <th style="width: 32%;">Tags</th>
      </tr>
    </thead>
    <tbody>
      {% for file in files %}
        <tr>
          <td>
            <input class="form-control" name="{% concatenate "file" file.id "name" %}" size=60 type="text" value="{{file.name}}" placeholder="A representative name of this file" required>
          </td>
          <td>
              <input class="form-control" name="{% concatenate "file" file.id "description" %}" size=60 type="text" value="{{file.description}}" placeholder="A description of this file" required>
          </td>
          <td>
            <input class="form-control" name="{% concatenate "file" file.id "tags" %}" type="text" size=60 value="{{file.tags}}" placeholder="comma, separated, list, of, tags" required>
          </td>
          <td>
            <button class="btn btn-secondary btn-sm text-danger" formaction="{% url 'project-admin:delete-file' file.id %}" formnovalidate>Delete</button>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="row text-center">
    <button class="btn btn-success" formaction="{% url 'project-admin:add-file' %}" formnovalidate>Add File</button>
    <input type="submit" class="btn btn-primary align-right" value="Save updates">
  </div>
</form>

{% endblock %}

project_admin/templates/project_admin/config-general-settings.html
{% extends 'main/application.html' %}

{% block content %}
{% load utilities %}

<form action="{% url 'project-admin:config-general-settings' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label>Project title</label> <input class="form-control" name="project_title" type="text" size=60 value="{{config.project_title}}" placeholder="My Open Humans Project">
  </div>
  <div class="form-group">
    <label>Project description</label> <input class="form-control" name="project_description" type="text" size=120 value="{{config.project_description}}" placeholder="This template demonstrates how you can run your own Open Humans data upload project">
  </div>
  <div class="form-group">
    <label>More info URL (optional)</label> <input class="form-control" name="more_info_url" type="text" size=60 value="{{config.more_info_url}}">
  </div>
  <div class="form-group">
    <label>Logo URL (optional)</label> <input class="form-control" name="logo_url" type="text" size=60 value="{{config.logo_url}}">
  </div>
  <input class="btn btn-default" type="submit" value="Save updates">
</form>

{% endblock %}

project_admin/templates/project_admin/config-homepage-text.html
{% extends 'main/application.html' %}

{% block content %}
{% load utilities %}
<p class="lead">
  You can use <a href="https://en.wikipedia.org/wiki/Markdown">
    Markdown</a> to write these pages. If you are new to this:
  <i>Github</i> has a <a href="https://guides.github.com/features/mastering-markdown/#syntax">
    good beginners guide on how to write Markdown</a>!
</p>

<form action="{% url 'project-admin:config-homepage-text' %}" method="post">
  {% csrf_token %}

  <label>
    About text
  </label>
  <div class="form-group">
    <textarea name="about" style="font-family:monospace;" class="form-control" rows=30 cols=110>{{config.about}}</textarea>
  </div>

  <label>
    FAQ
  </label>
  <div class="form-group">
    <textarea class="form-control" name="faq" style="font-family:monospace;" rows=30 cols=110>{{config.faq}}</textarea>
  </div>

  <label>
    Homepage text
  </label>
  <div class="form-group">
    <textarea class="form-control" name="homepage_text" style="font-family:monospace;" rows=30 cols=110>{{config.homepage_text}}</textarea>
  </div>

  <label>
    Overview
  </label>
  <div class="form-group">
    <textarea class="form-control" name="overview" style="font-family:monospace;" rows=30 cols=110>{{config.overview}}</textarea>
  </div>

  <label>
    Upload description
  </label>
  <div class="form-group">
    <textarea class="form-control" name="upload_description" style="font-family:monospace;" rows=30 cols=110>{{config.upload_description}}</textarea>
  </div>

  <input class="btn btn-default"  type="submit" value="Save update">
</form>

{% endblock %}

project_admin/templates/project_admin/config-oh-settings.html
{% extends 'main/application.html' %}

{% block content %}
{% load utilities %}

<form action="{% url 'project-admin:config-oh-settings' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label>Client ID</label> <input class="form-control" name="client_id" size=60 type="text" value="{{config.oh_client_id}}" placeholder="Enter your Open Humans Client-ID" required>
  </div>
  <div class="form-group">
    <label>Client secret</label> <input class="form-control" name="client_secret" type="text" size=60 value="{{config.oh_client_secret}}" placeholder="Enter your Open Humans Client-Secret" required>
  </div>
  <div class="form-group">
    <label>Activity page URL</label> <input class="form-control" name="activity_page" type="text" size=60 value="{{config.oh_activity_page}}" placeholder="Enter the Open Humans Activity Page URL">
  </div>
  <input type="submit" class="btn btn-default" value="Save updates">
</form>

{% endblock %}

project_admin/templates/project_admin/home.html
{% extends 'main/application.html' %}

{% block content %}
{% load utilities %}

<h1>Current Project Configuration</h1>

<h2>
  General information
  <a href="{% url 'project-admin:config-general-settings' %}" class="btn btn-primary">Edit general settings</a>
</h2>

<table class="table">
  <tbody>
    <tr>
      <th>Project title</th>
      <td>{{ config.project_title }}</td>
    </tr>
    <tr>
      <th>Project description</th>
      <td>{{ config.project_description }}</td>
    </tr>
    <tr>
      <th>More info URL (optional)</th>
      <td>
        {% if config.more_info_url %}
          {{ config.more_info_url }}
        {% else %}
          <i>Not defined.</i>
        {% endif %}
      </td>
    </tr>
    <tr>
      <th>Project logo URL</th>
      <td>
        {% if config.logo_url %}
          {{ config.logo_url }}
        {% else %}
          <i>Not defined. Logo defaults to:
            <code>/static/default_logo.png</code></i>
        {% endif %}
      </td>
    </tr>
    <tr>
      <th>Project logo</th>
      <td>
        <img alt="Brand" src="{% if config.logo_url %}{{config.logo_url}}{% else %}/static/default_logo.png{% endif %}" height="150px" align="left">
      </td>
    </tr>
  </tbody>
</table>

<hr>
<h2>
  Open Humans configurations
  <a href="{% url 'project-admin:config-oh-settings' %}" class="btn btn-primary">Edit Open Humans settings</a>
</h2>

<table class="table">
  <tbody>
    <tr>
      <th>Open Humans client ID (Required)</th>
      <td>{{ config.oh_client_id }}</td>
    </tr>
    <tr>
      <th>Open Humans client secret (Required)</th>
      <td>{{ config.oh_client_secret }}</td>
    </tr>
    <tr>
      <th>Open Humans activity page URL</th>
      <td><a href="{{ config.oh_activity_page }}">{{ config.oh_activity_page }}</a></td>
    </tr>
  </tbody>
</table>

<hr>
<h2>
  File information configurations
  <a href="{% url 'project-admin:config-file-settings' %}" class="btn btn-primary">Edit file settings</a>
</h2>

{% if files|length %}
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Tags</th>
    </tr>
  </thead>
  <tbody>
    {% for file in files %}
    <tr>
      <td>{{ file.name }}</td>
      <td>{{ file.description }}</td>
      <td>{{ file.tags }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<div class="text-center">
    <p class="lead">No files configured</p>
</div>
{% endif %}
<h2>
  Webpage content
  <a href="{% url 'project-admin:config-homepage-text' %}" class="btn btn-primary">Edit Webpage contents</a>
</h2>

<h3>About</h3>
<div class="well">
  {{ config.about|markdown }}
</div>

<h3>FAQ</h3>
<div class="well">
  {{ config.faq|markdown }}
</div>

<h3>Homepage text</h3>
<div class="well">
  {{ config.homepage_text|markdown }}
</div>

<h3>Overview</h3>
<div class="well">
  {{ config.overview|markdown }}
</div>

<h3>Upload Description</h3>
<div class="well">
  {{ config.upload_description|markdown }}
</div>

{% endblock %}

project_admin/templates/project_admin/login.html
{% extends 'main/application.html' %}

{% block content %}

{% if error %}
<div class="alert alert-danger" role="alert">
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only">Error:</span>
  {{ error }}
</div>
{% endif %}

<form action="{% url 'project-admin:login' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
  Admin password: <input type="password" class="form-control" name="password">
  </div>
  <input type="submit" value="Log in" class="btn btn-default">
</form>

{% endblock %}