main/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^complete/?$', views.complete, name='complete'),
    url(r'^logout/?$', views.logout_user, name='logout'),
    url(r'^overview/?$', views.overview, name='overview'),
    url(r'^upload_simple/?$', views.upload_old, name='upload_old'),
    url(r'^about/?$', views.about, name='about'),
    url(r'^list/?$', views.list_files, name='list'),
    url(r'^delete/(?P<file_id>\w+)/?$', views.delete_file, name='delete')
]

oh_data_uploader/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns = [
    path('project-admin/', include('project_admin.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

project_admin/urls.py
from django.conf.urls import url

from . import views

app_name = 'project-admin'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^config-general-settings/?$',
        views.config_general_settings, name='config-general-settings'),
    url(r'^config-oh-settings/?$',
        views.config_oh_settings, name='config-oh-settings'),
    url(r'^config-file-settings/?$',
        views.config_file_settings, name='config-file-settings'),
    url(r'^config-homepage-text/?$',
        views.config_homepage_text, name='config-homepage-text'),
    url(r'^login/?$', views.admin_login, name='login'),
    url(r'^add-file/?$', views.add_file, name='add-file'),
    url(r'^delete-file/(?P<file_id>\w+)/?$', views.delete_file,
        name='delete-file'),
]

main/views.py
import json
import logging
try:
    from urllib2 import HTTPError
except ImportError:
    from urllib.error import HTTPError

from django.conf import settings
from django.contrib.auth import login, logout
from django.shortcuts import redirect, render
from django.contrib import messages
from django.utils.safestring import mark_safe
from django.core.serializers import serialize

import ohapi
import requests

from project_admin.models import ProjectConfiguration, FileMetaData
from .helpers import oh_code_to_member

logger = logging.getLogger(__name__)

OH_BASE_URL = settings.OPENHUMANS_OH_BASE_URL
OH_API_BASE = OH_BASE_URL + '/api/direct-sharing'
OH_DIRECT_UPLOAD = OH_API_BASE + '/project/files/upload/direct/'
OH_DIRECT_UPLOAD_COMPLETE = OH_API_BASE + '/project/files/upload/complete/'

OH_OAUTH2_REDIRECT_URI = '{}/complete'.format(settings.OPENHUMANS_APP_BASE_URL)


def delete_file(request, file_id):
    """
    Delete specified file in Open Humans for this project member.
    """
    if request.user.is_authenticated and request.user.username != 'admin':
        oh_member = request.user.openhumansmember
        client_info = ProjectConfiguration.objects.get(id=1).client_info
        ohapi.api.delete_files(
            project_member_id=oh_member.oh_id,
            access_token=oh_member.get_access_token(**client_info),
            file_id=file_id)
        return redirect('list')
    return redirect('index')


def delete_all_oh_files(oh_member):
    """
    Delete all current project files in Open Humans for this project member.
    """
    client_info = ProjectConfiguration.objects.get(id=1).client_info
    ohapi.api.delete_files(
        project_member_id=oh_member.oh_id,
        access_token=oh_member.get_access_token(**client_info),
        all_files=True)


def raise_http_error(url, response, message):
    raise HTTPError(url, response.status_code, message, hdrs=None, fp=None)


def upload_file_to_oh(oh_member, filehandle, metadata):
    """
    This demonstrates using the Open Humans "large file" upload process.
    The small file upload process is simpler, but it can time out. This
    alternate approach is required for large files, and still appropriate
    for small files.
    This process is "direct to S3" using three steps: 1. get S3 target URL from
    Open Humans, 2. Perform the upload, 3. Notify Open Humans when complete.
    """
    client_info = ProjectConfiguration.objects.get(id=1).client_info

    # Get the S3 target from Open Humans.
    upload_url = '{}?access_token={}'.format(
        OH_DIRECT_UPLOAD, oh_member.get_access_token(**client_info))
    req1 = requests.post(upload_url,
                         data={'project_member_id': oh_member.oh_id,
                               'filename': filehandle.name,
                               'metadata': json.dumps(metadata)})
    if req1.status_code != 201:
        raise raise_http_error(upload_url, req1,
                               'Bad response when starting file upload.')

    # Upload to S3 target.
    req2 = requests.put(url=req1.json()['url'], data=filehandle)
    if req2.status_code != 200:
        raise raise_http_error(req1.json()['url'], req2,
                               'Bad response when uploading to target.')

    # Report completed upload to Open Humans.
    complete_url = ('{}?access_token={}'.format(
        OH_DIRECT_UPLOAD_COMPLETE, oh_member.get_access_token(**client_info)))
    req3 = requests.post(complete_url,
                         data={'project_member_id': oh_member.oh_id,
                               'file_id': req1.json()['id']})
    if req3.status_code != 200:
        raise raise_http_error(complete_url, req2,
                               'Bad response when completing upload.')


def iterate_files_upload(request):
    """
    iterate over all files to upload them to OH.
    """
    files = FileMetaData.objects.all()
    for file in files:
        uploaded_file = request.FILES.get('file_{}'.format(file.id))
        if uploaded_file is not None:
            metadata = {'tags': json.loads(file.tags),
                        'description': file.description}
            upload_file_to_oh(
                request.user.openhumansmember,
                uploaded_file,
                metadata)


def file_upload_prep_context(oh_member, proj_config):
    files = FileMetaData.objects.all()
    files_js = serialize('json', files)
    for file in files:
        file.tags = file.get_tags()
    context = {'oh_id': oh_member.oh_id,
               'oh_member': oh_member,
               'files': files,
               'files_js': files_js,
               'upload_description': proj_config.upload_description}
    return context


def set_auth_url(proj_config):
    if proj_config.oh_client_id:
        auth_url = ohapi.api.oauth2_auth_url(
            client_id=proj_config.oh_client_id,
            redirect_uri=OH_OAUTH2_REDIRECT_URI)
    else:
        auth_url = 'http://www.example.com'
    return auth_url


def index(request):
    """
    Starting page for app.
    """
    proj_config = ProjectConfiguration.objects.get(id=1)
    file_num = FileMetaData.objects.all().count()
    auth_url = set_auth_url(proj_config)
    if not proj_config.oh_client_secret or \
       not proj_config.oh_client_id or \
       not file_num:
        messages.info(request,
                      mark_safe(
                          "<b><a href='/project-admin'>"
                          "Click here to set up the app."
                          "</a></b>"
                      ))
    context = {'auth_url': auth_url,
               'index_page': "".join(proj_config.homepage_text),
               'file_num': file_num}
    if request.user.is_authenticated and request.user.username != 'admin':
        return redirect('overview')
    return render(request, 'main/index.html', context=context)


def overview(request):
    client_info = ProjectConfiguration.objects.get(id=1).client_info
    if request.user.is_authenticated and request.user.username != 'admin':
        oh_member = request.user.openhumansmember
        proj_config = ProjectConfiguration.objects.get(id=1)
        files = FileMetaData.objects.all()
        files_js = serialize('json', files)
        for file in files:
            file.tags = file.get_tags()
        context = {'oh_id': oh_member.oh_id,
                   'oh_member': oh_member,
                   'files': files,
                   'files_js': files_js,
                   'access_token': oh_member.get_access_token(**client_info),
                   "overview": "".join(proj_config.overview)}
        return render(request, 'main/overview.html', context=context)
    return redirect('index')


def login_member(request):
    code = request.GET.get('code', '')
    oh_member = oh_code_to_member(code=code)
    if oh_member:
        # Log in the user.
        user = oh_member.user
        login(request, user,
              backend='django.contrib.auth.backends.ModelBackend')


def complete(request):
    """
    Receive user from Open Humans. Store data, start data upload task.
    """
    logger.debug("Received user returning from Open Humans.")

    proj_config = ProjectConfiguration.objects.get(id=1)

    if request.method == 'GET':
        login_member(request)
        if not request.user.is_authenticated:
            logger.debug('Invalid code exchange. User returned to start page.')
            return redirect('/')
        else:
            oh_member = request.user.openhumansmember
        context = file_upload_prep_context(oh_member, proj_config)
        return render(request, 'main/complete.html',
                      context=context)

    elif request.method == 'POST':
        iterate_files_upload(request)
        return redirect('index')


def logout_user(request):
    """
    Logout user
    """
    if request.method == 'POST':
        logout(request)
    return redirect('index')


def upload_old(request):
    proj_config = ProjectConfiguration.objects.get(id=1)
    files = FileMetaData.objects.all()
    for file in files:
        file.tags = file.get_tags()
    if request.user.is_authenticated:
        context = {'upload_description': proj_config.upload_description,
                   'files': files}
        return render(request, 'main/upload_old.html',
                      context=context)
    return redirect('index')


def about(request):
    """
    Render about page
    """
    proj_config = ProjectConfiguration.objects.get(id=1)
    context = {'about': proj_config.about,
               'faq': proj_config.faq}
    return render(request, 'main/about.html',
                  context=context)


def list_files(request):
    if request.user.is_authenticated and request.user.username != 'admin':
        oh_member = request.user.openhumansmember
        client_info = ProjectConfiguration.objects.get(id=1).client_info
        data = ohapi.api.exchange_oauth2_member(
                    oh_member.get_access_token(**client_info))
        context = {'files': data['data']}
        return render(request, 'main/list.html',
                      context=context)
    return redirect('index')

main/templates/main/about.html
{% extends 'main/application.html' %}

{% block content %}
{% load utilities %}
<div class="row">
  <div class="col-md-6">
    {{about|markdown}}
  </div>
  <div class="col-md-6">
    <h1>FAQ</h1>
    {{faq|markdown}}
  </div>
</div>

{% endblock %}

main/templates/main/application.html
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{{config.project_title |default:"My Open Humans Project" }}</title>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=PT+Serif:400,700,400italic' rel='stylesheet' type='text/css'>
    <link href='https://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css' rel='stylesheet' type='text/css'>

    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>


    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    {% load static %}

    <style>
      body {
        padding-top: 20px;
        padding-bottom: 20px;
      }

      .navbar {
        margin-bottom: 20px;
      }


      /* Sticky footer styles
-------------------------------------------------- */
html {
  position: relative;
  min-height: 100%;
}
body {
  /* Margin bottom by footer height */
  margin-bottom: 60px;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  /* Set the fixed height of the footer here */
  height: 60px;
  background-color: #f5f5f5;
}


.fcontainer .text-muted {
  padding: 0 15px;
  margin: 20px 0;
}
    </style>
  </head>

  <body>
        <div class="container">

          <!-- Static navbar -->
          <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}">{{config.project_title}}</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <li {% if section == 'home' %} class="active" {%endif%}>
                    <a href="{% url 'index' %}">Home</a>
                  </li>
                  {% if is_admin %}
                  <li>
                    <a href="{% url 'project-admin:home' %}">Project config</a>
                  </li>
                  {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li {% if section == 'about' %} class="active" {%endif%}>
                    <a href="{% url 'about' %}">About</a>
                  </li>
                  {% if request.user.is_authenticated %}
                    {% if not is_admin %}
                    <li {% if section == 'list' %} class="active" {%endif%}>
                      <a href="{% url 'list' %}">File List</a>
                    </li>
                    {% endif %}
                  <li>
                    <form action="{% url 'logout' %}" method="post">{% csrf_token %}<input type="submit" value="Log out" style="margin-top:6px;" class="btn btn-default"></form>
                  </li>
                  {% endif %}
                </ul>
              </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
          </nav>

          {% if messages %}

            {% for message in messages %}
            <div class="alert alert-info" role="alert">
            {{ message }}
            </div>
            {% endfor %}

          {% endif %}
          {% block content %}
          {% endblock %}

        </div> <!-- /container -->
        <footer class="footer">
          <div class="fcontainer">
            <p class="text-muted">
              <a href="https://www.openhumans.org/create/">
                Create your own project on <i>Open Humans</i>
              </a>
            </p>
          </div>
        </footer>
  </body>
</html>

main/templates/main/complete.html
{% extends 'main/application.html' %}

{% block content %}

      <h1>One last step: Uploading your data to {{config.project_title}}</h1>
      <p class="lead">
        Thank you! We got your authorization to connect to <i>Open Humans</i>.
      </p>
      <div class="row">
        <div class="col-md-6">
          {% load utilities %}
          {{upload_description|markdown}}
        </div>
        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-body">
              {% include 'main/partials/upload_form.html' %}
            </div>
          </div>
          <p>
            You can also visit <a href="{{ oh_proj_page }}">this project's page on Open Humans </a>
            to see any data you've previously uploaded.
          </p>
        </div>
      </div>

{% endblock %}

main/templates/main/index.html
{% extends 'main/application.html' %}

{% block content %}

      <div class="jumbotron">
        <img alt="Brand" src="{% if config.logo_url %}{{config.logo_url}}{% else %}/static/default_logo.png{% endif %}" height="150px" align="left">
        <h1>Welcome to {{ config.project_title|default:"My Open Humans Project" }}</h1>
        <p>
          {{config.project_description|default:"This template demonstrates how you can run your own Open Humans data upload project"}}
        </p>
      </div>

      <div class="row">
        <div class="col-md-6">
          {% load utilities %}
          {{index_page|markdown}}
        </div>
        <div class="col-md-6">
          <h2>How it works</h2>
          <ol>
            <li><b>Log in or create an Open Humans account</b><br>
              You can upload your data for <i>{{config.project_title}}</i>
              once you have done this.
            </li>
            <li><b>Authorize {{config.project_title}} on <i>Open Humans</i></b><br>
              This authorizes us to deposit your archive into your Open Humans account.</li>
            <li><b>Upload your data.</b><br>
              You will be redirected back to {{config.project_title}} and can then
              upload your data.
              You'll be able to
              <a href="{{ oh_proj_page }}">access &amp; manage your data on
              Open Humans</a>.
            </li>
          </ol>

          {% if config.oh_client_id and config.oh_client_secret and file_num %}
          <a class="btn btn-primary btn-lg"
            href="{{ auth_url }}">
              Get started / Login
          </a>
          {% else %}
          <a class="btn btn-primary btn-lg"
            href="{% url 'project-admin:home' %}">
              Setup your project
          </a>
          {% endif %}
          <h2>FAQ</h2>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Will my data be public?</h3>
            </div>
            <div class="panel-body">
              <p>
                The short answer: No. The longer answer: No, unless you decide that
                you want to make this data public. If that is the case then you can head over to
                <a href="{{ oh_proj_page }}">Open Humans</a>.
                and make the full archive data publicly available.
              </p>
            </div>
          </div>
          <small>Have more questions?
            <a href="/about">
              Read the full FAQ and About page
            </a>.
          </small>
        </div>
      </div>


{%endblock%}

main/templates/main/list.html
{% extends 'main/application.html' %}

{% block content %}

    <h1>File List</h1>
    <p class="lead">This is a list of files you have uploaded to OpenHumans using this project.</p>

    {% if files|length %}
    <table class="table table-striped" >
        <thead>
            <tr>
                <th style="width: 10%;">Name</th>
                <th style="width: 40%;">Description</th>
                <th style="width: 40%;">Tags</th>
            </tr>
        </thead>
        <tbody>
        {% for file in files %}
        <tr>
            <td>{{ file.basename }}</td>
            <td>{{ file.metadata.description }}</td>
            <td>
                {% for tag in file.metadata.tags %}
                <span class="badge">{{ tag }}</span>
                {% endfor %}
            </td>
            <td>
                <a href="{{ file.download_url }}" class="btn btn-secondary btn-sm text-success" target="_blank">Download</a>
            </td>
            <td>
                <a href="{% url 'delete' file_id=file.id %}" class="btn btn-secondary btn-sm text-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="text-center">
        <p class="lead">No files uploaded</p>
    </div>
    {% endif %}

{% endblock %}

main/templates/main/overview.html
{% extends 'main/application.html' %}

{% block content %}

      <h1>Manage your {{config.project_title}} data.</h1>
      <p class="lead">
        Thank you! We logged you in through <i>Open Humans</i>.
      </p>
      <div class="row">
        <div class="col-md-6">
          {% load utilities %}
          {{overview|markdown}}
        </div>
        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-body">
              {% include 'main/partials/upload_form.html' %}
            </div>
          </div>
          <p>
            You can also take a look at the <a href="{% url 'list' %}">file list</a> or
            visit <a href="{{ oh_proj_page }}">this project's page on Open Humans </a>
            to see any data you've previously uploaded.
          </p>
        </div>
      </div>

{% endblock %}

main/templates/main/upload_old.html
{% extends 'main/application.html' %}

{% block content %}

<div class="row">
  <div class="col-md-6">
    {% load utilities %}
    {{upload_description|markdown}}
  </div>
  <div class="col-md-6">
    <h2>Upload your data</h2>

    <form method="post" enctype="multipart/form-data" action="{% url 'complete' %}">
      {% csrf_token %}
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Tags</th>
          </tr>
        </thead>
        <tbody>
        {% for file in files %}
          <tr>
            <td>{{ file.name }}</td>
            <td>{{ file.description }}</td>
            <td>{{ file.tags }}</td>
            <td>
                <input type="file" name="{% concatenate "file" file.id %}"
                       id="{% concatenate "file" file.id %}">
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      <input class="btn btn-primary" type="submit" value="Upload your data">
    </form>
    <p class="lead">
      A word of warning: <strong>This uploader does not work well for large files.</strong>
      If an upload takes longer than 30 seconds to finish the website
      will time out. In these cases <a href="{% url "index"%}">the use of the Javascript uploader</a> is preferred
      as it does not have this limitation.
    </p>
  </div>
</div>

{% endblock %}